### ISSUE TITLE
Missing column information

### ISSUE THREAD

**Issue by pumbogongles** [shaikhsajid1111/facebook_page_scraper#109]
1 - `posted_on` column in .csv file is empty. 
No errors when running the program but I do see a few `no post_url, skipping` in the terminal while it is running

2 - On some pages, like MetaSingapore page, everything runs fine with no error, but if I try pages like EssoSingapore, 
Errors like these appear
```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\facebook_page_scraper\facebook_page_scraper\element_finder.py", line 335, in __find_posted_time
    parse(aria_label_value).isoformat()
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\dateutil\parser\_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
```

Not sure if Meta has changed their dateTime or just an issue with my Python

3 - Is there a way to generate a json file instead of printing the json onto terminal?

**Comment by moda20** [comment]
This is still an issue when the date a tag doesn't have the exact time in html tags inside of it. soemtimes facebook uses a canvas there and the date only shows somewhere when you hover over the a tag.
