### ISSUE TITLE
ERROR - Error at find_posted_time method : Unknown string format: Enlarge

### ISSUE THREAD

**Issue by tom-a-horrocks** [shaikhsajid1111/facebook_page_scraper#116]
Thanks for writing this app. I've recently started receiving an error to do with datetime parsing from a page that was previously working, so I'm assuming FB must have changed something. It might be the same as issue #109. 

> 2024-06-05 07:42:57,254 - facebook_page_scraper.element_finder - ERROR - Error at find_posted_time method : Unknown string format: Enlarge
> Traceback (most recent call last):
>   File "<snip>\facebook_page_scraper\element_finder.py", line 337, in __find_posted_time
>     parse(aria_label_value).isoformat()
>     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "<snip>\dateutil\parser\_parser.py", line 1368, in parse
>     return DEFAULTPARSER.parse(timestr, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<snip>\dateutil\parser\_parser.py", line 643, in parse
>     raise ParserError("Unknown string format: %s", timestr)

**Comment by moda20** [comment]
I haver a fork that i have updated to handle the post_url and post time scraping correctly :
https://github.com/moda20/facebook_page_scraper
can you try it and see if it works for you

**Comment by tom-a-horrocks** [comment]
Thanks @moda20! I give it a try, but unfortunately I get the same error.

**Comment by shaikhsajid1111** [comment]
https://github.com/shaikhsajid1111/facebook_page_scraper/issues/115#issuecomment-2155218585
