### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'. Did you mean: 'SSLv23_METHOD'?

### ISSUE THREAD

**Issue by adildg** [shaikhsajid1111/facebook_page_scraper#35]
Hello,

When I try to import : 
```python
from facebook_page_scraper import Facebook_scraper
```
I get the following error : 

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mpl/Desktop/FaceBookPagesScraper/facebook_page_scraper/facebook_page_scraper/__init__.py", line 1, in <module>
    from .driver_initialization import Initializer
  File "/Users/mpl/Desktop/FaceBookPagesScraper/facebook_page_scraper/facebook_page_scraper/driver_initialization.py", line 3, in <module>
    from seleniumwire import webdriver
  File "/opt/homebrew/lib/python3.10/site-packages/selenium_wire-4.3.1-py3.10.egg/seleniumwire/webdriver.py", line 13, in <module>
    from seleniumwire import backend
  File "/opt/homebrew/lib/python3.10/site-packages/selenium_wire-4.3.1-py3.10.egg/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/opt/homebrew/lib/python3.10/site-packages/selenium_wire-4.3.1-py3.10.egg/seleniumwire/server.py", line 4, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "/opt/homebrew/lib/python3.10/site-packages/selenium_wire-4.3.1-py3.10.egg/seleniumwire/handler.py", line 5, in <module>
    from seleniumwire import har
  File "/opt/homebrew/lib/python3.10/site-packages/selenium_wire-4.3.1-py3.10.egg/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/opt/homebrew/lib/python3.10/site-packages/selenium_wire-4.3.1-py3.10.egg/seleniumwire/thirdparty/mitmproxy/connections.py", line 9, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/opt/homebrew/lib/python3.10/site-packages/selenium_wire-4.3.1-py3.10.egg/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 43, in <module>
    "SSLv2": (SSL.SSLv2_METHOD, BASIC_OPTIONS),
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'. Did you mean: 'SSLv23_METHOD'?
```

I have tried downgrading to PyOpenSSL==22.0.0.0 didn't resolve the issue

**Comment by shaikhsajid1111** [comment]
Okay, Can you share a bit of information about your environment?

**Comment by shaikhsajid1111** [comment]
Did you tried `21.0.0` as well? 🤔

**Comment by kareemrasheed89** [comment]
> Did you tried `21.0.0` as well? 🤔

Please what do i need to downgrade??? what is the 21.0.0 here

**Comment by antonioromero** [comment]
> Did you tried `21.0.0` as well? thinking

What do you mean here? This project, one library or the browser?
This project ist actually at v4, isn't it?

**Comment by kareemrasheed89** [comment]
> > Did you tried `21.0.0` as well? 🤔
> 
> Please what do i need to downgrade??? what is the 21.0.0 here

**Comment by antonioromero** [comment]
> I have tried downgrading to PyOpenSSL==22.0.0.0 didn't resolve the issue
PyOpenSSL==21.0.0
