### ISSUE TITLE
SSL_CTX_set_ecdh_auto Error

### ISSUE THREAD

**Issue by billwright** [shaikhsajid1111/facebook_page_scraper#40]
I'm trying to get the example in the README to work. I first encountered the issue with SSL and downgraded to version 21.0.0. I then ran the example code with the only change to the browser type. I used "chrome" instead of "firefox". I got the error below. I'm on a Mac (OS 10.15.7), Intel hardware, running Python 3.11 with the following packages installed:

async-generator       1.10
attrs                 22.1.0
beautifulsoup4        4.11.1
blinker               1.5
certifi               2022.9.24
cffi                  1.15.1
charset-normalizer    2.1.1
colorama              0.4.6
configparser          5.3.0
crayons               0.4.0
cryptography          38.0.3
facebook-page-scraper 4.0.1
google                3.0.0
h11                   0.14.0
h2                    4.1.0
hpack                 4.0.0
html5lib              1.1
hyperframe            6.0.1
idna                  3.4
kaitaistruct          0.10
outcome               1.2.0
pip                   22.3.1
pyasn1                0.4.8
pycparser             2.21
pyOpenSSL             21.0.0
pyparsing             3.0.9
PySocks               1.7.1
python-dateutil       2.8.2
requests              2.28.1
selenium              4.1.0
selenium-wire         4.3.1
setuptools            65.5.0
six                   1.16.0
sniffio               1.3.0
sortedcontainers      2.4.0
soupsieve             2.3.2.post1
termcolor             2.1.0
trio                  0.22.0
trio-websocket        0.9.2
urllib3               1.26.12
urllib3-secure-extra  0.1.0
webdriver-manager     3.2.2
webencodings          0.5.1
wsproto               1.2.0

Also, I'm trying to scrape information from the top-level page, specifically the email address. Can this library do that?

[WDM] - Current google-chrome version is 107.0.5304
[WDM] - Get LATEST driver version for 107.0.5304
[WDM] - There is no [mac64] chromedriver for browser 107.0.5304 in cache
[WDM] - Get LATEST driver version for 107.0.5304
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64.zip
[WDM] - Driver has been saved in cache [/Users/bwright/.wdm/drivers/chromedriver/mac64/107.0.5304.62]
127.0.0.1:64896: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/server.py", line 113, in handle
    root_layer()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 285, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http1.py", line 100, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 205, in __call__
    if not self._process_flow(flow):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 304, in _process_flow
    return self.handle_regular_connect(f)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 223, in handle_regular_connect
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 445, in _establish_tls_with_server
    self.server_conn.establish_tls(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 290, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/net/tcp.py", line 382, in convert_to_tls
    context = tls.create_client_context(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 276, in create_client_context
    context = _create_ssl_context(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 163, in _create_ssl_context
    context = SSL.Context(method)
              ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/SSL.py", line 674, in __init__
    res = _lib.SSL_CTX_set_ecdh_auto(context, 1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'

**Comment by shaikhsajid1111** [comment]
I don't know much about this error, it is much more likely related to dependency, not the library. I don't think it can scrape email addresses

**Comment by kareemrasheed89** [comment]
When I got this error, I went to edit the driver_utilities.py document and re-indent my "allow_span html line of code" and it works....the next error am getting now is the "List index out of range" error
