### ISSUE TITLE
Running the library in Linux Debian 8.11

### ISSUE THREAD

**Issue by kokohandoko00** [shaikhsajid1111/facebook_page_scraper#46]
I have a server that build with os Debian 8.11 (jessie). When I try to run the code, i get this error

`[WDM] - Driver [/home/cucakrowo/.wdm/drivers/geckodriver/linux64/v0.32.1/geckodriver] found in cache
2023-02-06 18:20:25,350 - facebook_page_scraper.scraper - ERROR - Error at scrap_to_csv : Message: Process unexpectedly closed with status 1
Traceback (most recent call last):
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/facebook_page_scraper/scraper.py", line 151, in scrap_to_csv
    data = self.scrap_to_json()  # get the data in JSON format from the same class method
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/facebook_page_scraper/scraper.py", line 80, in scrap_to_json
    self.__start_driver()
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/facebook_page_scraper/scraper.py", line 60, in __start_driver
    self.browser, self.proxy, self.headless, self.browser_profile).init()
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/facebook_page_scraper/driver_initialization.py", line 90, in init
    driver = self.set_driver_for_browser(self.browser_name)
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/facebook_page_scraper/driver_initialization.py", line 83, in set_driver_for_browser
    return webdriver.Firefox(executable_path=GeckoDriverManager().install(), options=self.set_properties(browser_option))
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/seleniumwire/webdriver.py", line 75, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 183, in __init__
    keep_alive=True)
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/cucakrowo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1`

Is this because this library is not compatible with my OS, or are there any configuration that I have to set??

**Comment by shaikhsajid1111** [comment]
Are you running in headless mode? I can't understand what's the issue for crash by this log

**Comment by eric09230** [comment]
I believe u will need >python 3.8 to run(I'm running on python 3.11.0 ,Debian10)
try pyenv and install higher version
