### ISSUE TITLE
At Import: AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'

### ISSUE THREAD

**Issue by SchmueI** [shaikhsajid1111/facebook_page_scraper#62]
When trying to import the module, I get the following:

```
>>> from facebook_page_scraper import Facebook_scraper as fbscrape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/.local/lib/python3.9/site-packages/facebook_page_scraper/__init__.py", line 1, in <module>
    from .driver_initialization import Initializer
  File "/home/USER/.local/lib/python3.9/site-packages/facebook_page_scraper/driver_initialization.py", line 3, in <module>
    from seleniumwire import webdriver
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/webdriver.py", line 13, in <module>
    from seleniumwire import backend
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/server.py", line 4, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/handler.py", line 5, in <module>
    from seleniumwire import har
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 9, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 43, in <module>
    "SSLv2": (SSL.SSLv2_METHOD, BASIC_OPTIONS),
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'

```

Is this a known issue? Searching the internet, I didnt found any useful solutions...

Thx in advance

**Comment by SchmueI** [comment]
I have managed to "solve" the issue by hacking myself thru the modules:

In the file
`/home/USER/.local/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py` line 43f [VERSION_CHOICES]
I changed:
```
"SSLv2": (SSL.SSLv2_METHOD, BASIC_OPTIONS),
"SSLv3": (SSL.SSLv3_METHOD, BASIC_OPTIONS),
```
to:
```
"SSLv2": (SSL.SSLv23_METHOD, BASIC_OPTIONS),
"SSLv3": (SSL.SSLv23_METHOD, BASIC_OPTIONS),
```

And in line 51f  [METHOD_NAMES] I commented the two options out 
```
#SSL.SSLv2_METHOD: "SSLv2",
#SSLv3_METHOD: "SSLv3",
```

However, this led me to another error:

```
>>> json = meta_ai.scrap_to_json()
[WDM] - Driver [/home/demo/.wdm/drivers/geckodriver/linux64/v0.33.0/geckodriver] found in cache
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/.local/lib/python3.9/site-packages/facebook_page_scraper/scraper.py", line 82, in scrap_to_json
    self.__start_driver()
  File "/home/USER/.local/lib/python3.9/site-packages/facebook_page_scraper/scraper.py", line 61, in __start_driver
    self.__driver = Initializer(
  File "/home/USER/.local/lib/python3.9/site-packages/facebook_page_scraper/driver_initialization.py", line 90, in init
    driver = self.set_driver_for_browser(self.browser_name)
  File "/home/USER/.local/lib/python3.9/site-packages/facebook_page_scraper/driver_initialization.py", line 83, in set_driver_for_browser
    return webdriver.Firefox(executable_path=GeckoDriverManager().install(), options=self.set_properties(browser_option))
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/webdriver.py", line 61, in __init__
    self.proxy = backend.create(
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/backend.py", line 35, in create
    proxy = MitmProxy(addr, port, options)
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/server.py", line 43, in __init__
    mitmproxy_opts = Options(
  File "/home/USER/.local/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/options.py", line 147, in __init__
    choices=list(tls.VERSION_CHOICES.keys()),
AttributeError: module 'seleniumwire.thirdparty.mitmproxy.net.tls' has no attribute 'VERSION_CHOICES'
```

I faced this error successfully by commenting the Line 147 in file  `/home/USER/.local/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/options.py  ` out [self.add_option]:

`#choices=list(tls.VERSION_CHOICES.keys()),`

After those changes, the scraper works just fine. I assume that this procedure is not recommended for production purpose. However it might be a work-around for some cases.

I would be

**Comment by SchmueI** [comment]
After those changes, the scraper works just fine. I assume that this procedure is not recommended for production purpose. However it might be a work-around for some cases.

I didnt meant to close the issue. As the issue isnt solved, theres just a messy workaround :)

**Comment by davidkurtenb** [comment]
Even after commenting out line #147 #choices=list(tls.VERSION_CHOICES.keys()), I'm still getting the error AttributeError: module 'seleniumwire.thirdparty.mitmproxy.net.tls' has no attribute 'VERSION_CHOICES'. Any workarounds?

**Comment by peter279k** [comment]
After tracing these exception messages, the problem is about the `selenium-wire` package and the related commit is available [here](https://github.com/wkeeling/selenium-wire/commit/7ba19dee6027f0b6a7c383aeb0d9f6cb6045270a).

The current solution is to upgrade the `selenium-wire` package to the `5.1.0` version.

Once upgrading the above package version, it should drop `Python 3.6` version support in this package because the latest `selenium-wire` supports `Python 3.7+` version only.
