### ISSUE TITLE
I cant run the code

### ISSUE THREAD

**Issue by diegozl** [shaikhsajid1111/facebook_page_scraper#74]
Hello, I'm trying to run the system, but it's giving several errors. Here is the code used:

`from facebook_page_scraper import Facebook_scraper

page_name = "nameofpage"
posts_count = 10
browser = "firefox"
timeout = 60 #Seconds
headless = True
meta_ai = Facebook_scraper(page_name, posts_count, browser, timeout=timeout, headless=headless)

#call the scrap_to_json() method
#json_data = scraped_data.scrap_to_json()

filename = "data_file"
directory = "./"
meta_ai.scrap_to_csv(filename, directory)`

Now, the errors occurred:

> Traceback (most recent call last):
>   File "C:\Users\Diego\OneDrive\Documentos\VS\DelPaseo\main.py", line 1, in <module>
>     from facebook_page_scraper import Facebook_scraper
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\facebook_page_scraper\__init__.py", line 1, in <module>
>     from .driver_initialization import Initializer
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\facebook_page_scraper\driver_initialization.py", line 3, in <module>  
>     from seleniumwire import webdriver
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\webdriver.py", line 13, in <module>
>     from seleniumwire import backend
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\backend.py", line 4, in <module>
>     from seleniumwire.server import MitmProxy
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\server.py", line 4, in <module>
>     from seleniumwire.handler import InterceptRequestHandler
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\handler.py", line 5, in <module>
>     from seleniumwire import har
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\har.py", line 11, in <module>
>     from seleniumwire.thirdparty.mitmproxy import connections
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 9, in <module>
>     from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
>   File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 43, in <module>   
>     "SSLv2": (SSL.SSLv2_METHOD, BASIC_OPTIONS),
> AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'. Did you mean: 'SSLv23_METHOD'?

My objective was to post the posts of a certain page, in order to verify if there would be a certain mention in one of the posts. Does anyone know how to proceed? :/

**Comment by mystvictor** [comment]
Hi, 
Update selenium wire to version 5.1.0, this issue has been addressed. 
You can either uninstall the current version and re-install it (pip uninstall selenium-wire / pip install selenium-wire)
