### ISSUE TITLE
WebDriver.__init__() got an unexpected keyword argument 'executable_path'

### ISSUE THREAD

**Issue by arinewhouse** [shaikhsajid1111/facebook_page_scraper#81]
Not sure what the issue is here.

---

Traceback (most recent call last):
  File "c:\Users\***\Code\facebook_page_scraper\testing.py", line 14, in <module>
    json_data = meta_ai.scrap_to_json()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\\***\\Code\facebook_page_scraper\facebook_page_scraper\scraper.py", line 81, in scrap_to_json
    self.__start_driver()
  File "c:\Users\\***\\Code\facebook_page_scraper\facebook_page_scraper\scraper.py", line 58, in __start_driver
    self.browser, self.proxy, self.headless).init()
                                             ^^^^^^
  File "c:\Users\\***\\Code\facebook_page_scraper\facebook_page_scraper\driver_initialization.py", line 79, in init
    driver = self.set_driver_for_browser(self.browser_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\\***\\Code\facebook_page_scraper\facebook_page_scraper\driver_initialization.py", line 68, in set_driver_for_browser
    return webdriver.Firefox(executable_path=GeckoDriverManager().install(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium_wire-5.1.0-py3.11.egg\seleniumwire\webdriver.py", line 179, in __init__
    super().__init__(*args, **kwargs)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

--- 

I'm running the example script in the README

**Comment by shaikhsajid1111** [comment]
What's your selenium version?
