### ISSUE TITLE
driver error

### ISSUE THREAD

**Issue by ihabpalamino** [shaikhsajid1111/facebook_page_scraper#82]
hello i am getting this error related to browser [2023-08-02 16:57:15,952] ERROR in app: Exception on /scrape-facebook [POST]
Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\HP Probook\PycharmProjects\scraping-scripts\facebook.py", line 52, in scrape_facebook_page
    json_data = namepage.scrap_to_json(plateforme_name="facebook")
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\facebook_page_scraper\scraper.py", line 82, in scrap_to_json
    self.__start_driver()
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\facebook_page_scraper\scraper.py", line 61, in __start_driver
    self.__driver = Initializer(
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\facebook_page_scraper\driver_initialization.py", line 90, in init
    driver = self.set_driver_for_browser(self.browser_name)
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\facebook_page_scraper\driver_initialization.py", line 66, in set_driver_for_browser
    return webdriver.Chrome(executable_path=ChromeDriverManager().install(),
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\webdriver_manager\chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\webdriver_manager\manager.py", line 22, in _get_driver_path
    driver_version = driver.get_version()
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\webdriver_manager\driver.py", line 40, in get_version
    return self.get_latest_release_version()
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\webdriver_manager\driver.py", line 64, in get_latest_release_version
    validate_response(resp)
  File "C:\Users\HP Probook\PycharmProjects\scrap-scripts\venv\lib\site-packages\webdriver_manager\utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url http://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

**Comment by SaranaraSauce** [comment]
I'm having the same issue. Following.

**Comment by matejdro** [comment]
Solution appears to be to update webdriver-manager:

`python3 -m pip install webdriver-manager --upgrade`

(from https://stackoverflow.com/a/76922601/5273071)

**Comment by rihemansour** [comment]
Hello, in the setup.py you'll fing requirements = ['selenium==4.1.0',
                'webdriver-manager==3.2.2',
                'selenium-wire==5.1.0',
                'python-dateutil==2.8.2']
 change the 3.2.2 to 4.0.1

**Comment by Irene933** [comment]
I'm having the same issue here!
